# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import star_sensing_pb2 as star__sensing__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in star_sensing_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SensingServiceStub:
    """============================================================
    Service Definitions
    ============================================================

    / The main sensing service — runs on the Engine, consumed by Dashboard & Python.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamMeasurements = channel.unary_stream(
                '/star_sensing.SensingService/StreamMeasurements',
                request_serializer=star__sensing__pb2.StreamRequest.SerializeToString,
                response_deserializer=star__sensing__pb2.MeasurementBatch.FromString,
                _registered_method=True)
        self.StreamEnvironmentState = channel.unary_stream(
                '/star_sensing.SensingService/StreamEnvironmentState',
                request_serializer=star__sensing__pb2.StreamRequest.SerializeToString,
                response_deserializer=star__sensing__pb2.EnvironmentStateMsg.FromString,
                _registered_method=True)
        self.GetCurrentNetworks = channel.unary_unary(
                '/star_sensing.SensingService/GetCurrentNetworks',
                request_serializer=star__sensing__pb2.Empty.SerializeToString,
                response_deserializer=star__sensing__pb2.NetworkListResponse.FromString,
                _registered_method=True)
        self.GetSavedNetworks = channel.unary_unary(
                '/star_sensing.SensingService/GetSavedNetworks',
                request_serializer=star__sensing__pb2.SavedNetworkRequest.SerializeToString,
                response_deserializer=star__sensing__pb2.SavedNetworkListResponse.FromString,
                _registered_method=True)
        self.TriggerScan = channel.unary_unary(
                '/star_sensing.SensingService/TriggerScan',
                request_serializer=star__sensing__pb2.Empty.SerializeToString,
                response_deserializer=star__sensing__pb2.ScanResponse.FromString,
                _registered_method=True)
        self.ResetBaseline = channel.unary_unary(
                '/star_sensing.SensingService/ResetBaseline',
                request_serializer=star__sensing__pb2.Empty.SerializeToString,
                response_deserializer=star__sensing__pb2.Empty.FromString,
                _registered_method=True)
        self.GetHistory = channel.unary_unary(
                '/star_sensing.SensingService/GetHistory',
                request_serializer=star__sensing__pb2.HistoryRequest.SerializeToString,
                response_deserializer=star__sensing__pb2.HistoryResponse.FromString,
                _registered_method=True)


class SensingServiceServicer:
    """============================================================
    Service Definitions
    ============================================================

    / The main sensing service — runs on the Engine, consumed by Dashboard & Python.
    """

    def StreamMeasurements(self, request, context):
        """/ Stream real-time scan batches as they occur.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamEnvironmentState(self, request, context):
        """/ Stream processed environment state updates.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCurrentNetworks(self, request, context):
        """/ Get the current snapshot of all detected networks.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSavedNetworks(self, request, context):
        """/ Get saved access point metadata and aggregate RSSI statistics.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TriggerScan(self, request, context):
        """/ Trigger a manual scan.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetBaseline(self, request, context):
        """/ Reset the motion detection baseline.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHistory(self, request, context):
        """/ Get historical measurements for a specific BSSID.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SensingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamMeasurements': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamMeasurements,
                    request_deserializer=star__sensing__pb2.StreamRequest.FromString,
                    response_serializer=star__sensing__pb2.MeasurementBatch.SerializeToString,
            ),
            'StreamEnvironmentState': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamEnvironmentState,
                    request_deserializer=star__sensing__pb2.StreamRequest.FromString,
                    response_serializer=star__sensing__pb2.EnvironmentStateMsg.SerializeToString,
            ),
            'GetCurrentNetworks': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCurrentNetworks,
                    request_deserializer=star__sensing__pb2.Empty.FromString,
                    response_serializer=star__sensing__pb2.NetworkListResponse.SerializeToString,
            ),
            'GetSavedNetworks': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSavedNetworks,
                    request_deserializer=star__sensing__pb2.SavedNetworkRequest.FromString,
                    response_serializer=star__sensing__pb2.SavedNetworkListResponse.SerializeToString,
            ),
            'TriggerScan': grpc.unary_unary_rpc_method_handler(
                    servicer.TriggerScan,
                    request_deserializer=star__sensing__pb2.Empty.FromString,
                    response_serializer=star__sensing__pb2.ScanResponse.SerializeToString,
            ),
            'ResetBaseline': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetBaseline,
                    request_deserializer=star__sensing__pb2.Empty.FromString,
                    response_serializer=star__sensing__pb2.Empty.SerializeToString,
            ),
            'GetHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHistory,
                    request_deserializer=star__sensing__pb2.HistoryRequest.FromString,
                    response_serializer=star__sensing__pb2.HistoryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'star_sensing.SensingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('star_sensing.SensingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SensingService:
    """============================================================
    Service Definitions
    ============================================================

    / The main sensing service — runs on the Engine, consumed by Dashboard & Python.
    """

    @staticmethod
    def StreamMeasurements(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/star_sensing.SensingService/StreamMeasurements',
            star__sensing__pb2.StreamRequest.SerializeToString,
            star__sensing__pb2.MeasurementBatch.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamEnvironmentState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/star_sensing.SensingService/StreamEnvironmentState',
            star__sensing__pb2.StreamRequest.SerializeToString,
            star__sensing__pb2.EnvironmentStateMsg.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCurrentNetworks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/star_sensing.SensingService/GetCurrentNetworks',
            star__sensing__pb2.Empty.SerializeToString,
            star__sensing__pb2.NetworkListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSavedNetworks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/star_sensing.SensingService/GetSavedNetworks',
            star__sensing__pb2.SavedNetworkRequest.SerializeToString,
            star__sensing__pb2.SavedNetworkListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TriggerScan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/star_sensing.SensingService/TriggerScan',
            star__sensing__pb2.Empty.SerializeToString,
            star__sensing__pb2.ScanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResetBaseline(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/star_sensing.SensingService/ResetBaseline',
            star__sensing__pb2.Empty.SerializeToString,
            star__sensing__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/star_sensing.SensingService/GetHistory',
            star__sensing__pb2.HistoryRequest.SerializeToString,
            star__sensing__pb2.HistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SignalProcessorServiceStub:
    """/ Signal processing service — runs on Python, consumed by Engine.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessBatch = channel.unary_unary(
                '/star_sensing.SignalProcessorService/ProcessBatch',
                request_serializer=star__sensing__pb2.MeasurementBatch.SerializeToString,
                response_deserializer=star__sensing__pb2.ProcessingResult.FromString,
                _registered_method=True)
        self.StreamProcess = channel.stream_stream(
                '/star_sensing.SignalProcessorService/StreamProcess',
                request_serializer=star__sensing__pb2.MeasurementBatch.SerializeToString,
                response_deserializer=star__sensing__pb2.ProcessingResult.FromString,
                _registered_method=True)


class SignalProcessorServiceServicer:
    """/ Signal processing service — runs on Python, consumed by Engine.
    """

    def ProcessBatch(self, request, context):
        """/ Process a batch of raw measurements and return analysis results.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamProcess(self, request_iterator, context):
        """/ Stream continuous processing: send batches, receive results.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SignalProcessorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessBatch,
                    request_deserializer=star__sensing__pb2.MeasurementBatch.FromString,
                    response_serializer=star__sensing__pb2.ProcessingResult.SerializeToString,
            ),
            'StreamProcess': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamProcess,
                    request_deserializer=star__sensing__pb2.MeasurementBatch.FromString,
                    response_serializer=star__sensing__pb2.ProcessingResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'star_sensing.SignalProcessorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('star_sensing.SignalProcessorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SignalProcessorService:
    """/ Signal processing service — runs on Python, consumed by Engine.
    """

    @staticmethod
    def ProcessBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/star_sensing.SignalProcessorService/ProcessBatch',
            star__sensing__pb2.MeasurementBatch.SerializeToString,
            star__sensing__pb2.ProcessingResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamProcess(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/star_sensing.SignalProcessorService/StreamProcess',
            star__sensing__pb2.MeasurementBatch.SerializeToString,
            star__sensing__pb2.ProcessingResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
